# Generated by Django 2.2.6 on 2019-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(choices=[('unit', '单位'), ('dept', '部门')], default='dept', max_length=20, verbose_name='类型'),
        ),
    ]
