# Generated by Django 2.1.4 on 2020-01-19 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000, verbose_name='日程')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('allday', models.BooleanField(default=False, verbose_name='全天')),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日历日程',
                'verbose_name_plural': '日历日程',
                'ordering': ['start', '-end'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='事件类型')),
                ('color', models.CharField(max_length=10, verbose_name='表示颜色')),
            ],
            options={
                'verbose_name': '事件类型',
                'verbose_name_plural': '事件类型',
            },
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mydesk.EventType', verbose_name='日程类型'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
